User.create!([
  { name: "user5", email: "user5@test.com", password_digest: "$2a$12$COKcH.aC96Zc4CD5wTJzh.nBXfxMSzpmvIpvs7J5zXd4hnUkVhQEG", admin: true },
])
Supplier.create!([
  { name: "Harper-Collins", email: "hc@test.com", phone_number: "123-456-7890" },
  { name: "Macmillan Publishers", email: "mm@test.com", phone_number: "222-222-2222" },
  { name: "Penguin Random House", email: "prh@test.com", phone_number: "333-333-3333" },
  { name: "TestPublisher", email: "testpublisher@test.com", phone_number: "000-000-0000" },
])
Product.create!([
  { name: "The Odyssey", price: "4.99", description: "Odysseus' reliance on his wit and wiliness for survival in his encounters with divine and natural forces during his ten-year voyage home to Ithaca after the Trojan War is at once a timeless human story and an individual test of moral endurance.", inventory: nil, supplier_id: 2, active: true },
  { name: "Frankenstein", price: "9.99", description: "Few creatures of horror have seized readers' imaginations and held them for so long as the anguished monster of Mary Shelley's Frankenstein. The story of Victor Frankenstein's terrible creation and the havoc it caused has enthralled generations of readers and inspired countless writers of horror and suspense. Considering the gothic novel's enduring success, it is remarkable that it began merely as a whim of Lord Byron's.", inventory: nil, supplier_id: 3, active: true },
  { name: "Meditations", price: "9.99", description: "Written in Greek by an intellectual Roman emperor without any intention of publication, the Meditations of Marcus Aurelius  offer a wide range of fascinating spiritual reflections and exercises developed as the leader struggled to understand himself and make sense of the universe.", inventory: nil, supplier_id: 2, active: true },
  { name: "Crime and Punishment", price: "13.99", description: "Raskolnikov, a destitute and desperate former student, wanders through the slums of St Petersburg and commits a random murder without remorse or regret. He imagines himself to be a great man, a Napoleon: acting for a higher purpose beyond conventional moral law.", inventory: nil, supplier_id: 2, active: true },
  { name: "War and Peace", price: "12.99", description: "War and Peace begins at a glittering society party in St Petersburg in 1805, where conversations are dominated by the prospect of war. Terror swiftly engulfs the country as Napoleon's army marches on Russia, and the lives of three young people are changed forever.", inventory: nil, supplier_id: 2, active: true },
  { name: "The Republic", price: "9.49", description: "Presented in the form of a dialogue between Socrates and three different interlocutors, it is an inquiry into the notion of a perfect community and the ideal individual within it. During the conversation other questions are raised: what is goodness; what is reality; what is knowledge?", inventory: nil, supplier_id: 2, active: true },
  { name: "Paradise Lost", price: "7.99", description: "In Paradise Lost Milton produced poem of epic scale, conjuring up a vast, awe-inspiring cosmos and ranging across huge tracts of space and time, populated by a memorable gallery of grotesques. And yet, in putting a charismatic Satan and naked, innocent Adam and Eve at the centre of this story, he also created an intensely human tragedy on the Fall of Man.", inventory: nil, supplier_id: 2, active: true },
  { name: "The Brothers Karamazov", price: "14.99", description: "When brutal landowner Fyodor Karamazov is murdered, the lives of his sons are changed irrevocably: Mitya, the sensualist, whose bitter rivalry with his father immediately places him under suspicion for parricide; Ivan, the intellectual, whose mental tortures drive him to breakdown; the spiritual Alyosha, who tries to heal the family's rifts; and the shadowy figure of their bastard half-brother Smerdyakov.", inventory: nil, supplier_id: 2, active: true },
  { name: "Pride and Prejudice", price: "7.99", description: "When Elizabeth Bennet first meets eligible bachelor Fitzwilliam Darcy, she thinks him arrogant and conceited; he is indifferent to her good looks and lively mind. When she later discovers that Darcy has involved himself in the troubled relationship between his friend Bingley and her beloved sister Jane, she is determined to dislike him more than ever.", inventory: 1, supplier_id: 2, active: true },
  { name: "The Count of Monte Cristo", price: "8.99", description: "Thrown in prison for a crime he has not committed, Edmond Dantes is confined to the grim fortress of If. There he learns of a great hoard of treasure hidden on the Isle of Monte Cristo and he becomes determined not only to escape, but also to unearth the treasure and use it to plot the destruction of the three men responsible for his incarceration.", inventory: 1, supplier_id: 2, active: true },
  { name: "The Power and the Glory", price: "8.99", description: "In the Mexican state of Tabasco in the 1930s, all vestiges of Catholicism are being outlawed by the government. As churches are razed, icons are banned, and the price of devotion is execution, an unnamed member of the clergy flees. He’s known only as the 'whisky priest.'", inventory: nil, supplier_id: 2, active: true },
])

Image.create!([
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71RZuClkzaL._SL1200_.jpg", product_id: 1 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/91NOp9H2jJL._SL1500_.jpg", product_id: 11 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81bAXZAp-GL._SL1500_.jpg", product_id: 4 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/91CruT8BKOL._SL1500_.jpg", product_id: 2 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51RcuPqc+lL._SL1200_.jpg", product_id: 10 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81NLDvyAHrL._SL1500_.jpg", product_id: 9 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81DFDGzHZqL._SL1500_.jpg", product_id: 3 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/91JDB-Dm8sL._SL1500_.jpg", product_id: 5 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/91VLH-RiffL._SL1500_.jpg", product_id: 7 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/91nYfNvYa7L._SL1500_.jpg", product_id: 6 },
  { url: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/917QNDtEGML._SL1500_.jpg", product_id: 8 },
])
Category.create!([
  { name: "Fiction" },
  { name: "Non-Fiction" },
  { name: "Mystery" },
  { name: "Biography" },
  { name: "History" },
  { name: "Philosophy" },
  { name: "Children's" },
  { name: "Horror" },
  { name: "Romance" },
  { name: "Theology" },
  { name: "Adventure" },
])
CategoryProduct.create!([
  { category_id: 1, product_id: 1 },
  { category_id: 1, product_id: 2 },
  { category_id: 1, product_id: 4 },
  { category_id: 1, product_id: 5 },
  { category_id: 1, product_id: 6 },
  { category_id: 1, product_id: 7 },
  { category_id: 1, product_id: 8 },
  { category_id: 1, product_id: 9 },
  { category_id: 1, product_id: 10 },
  { category_id: 1, product_id: 11 },
  { category_id: 2, product_id: 3 },
  { category_id: 6, product_id: 3 },
  { category_id: 6, product_id: 4 },
  { category_id: 6, product_id: 5 },
  { category_id: 6, product_id: 6 },
  { category_id: 8, product_id: 2 },
  { category_id: 9, product_id: 9 },
  { category_id: 10, product_id: 7 },
  { category_id: 10, product_id: 8 },
  { category_id: 11, product_id: 1 },
  { category_id: 11, product_id: 10 },
  { category_id: 11, product_id: 11 },
])
